name: Build

on:
  push:
    tags:
      - "*.*.*"

permissions:
  actions: read
  contents: write

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - arm64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apple/swift-protobuf
          ref: '1.29.0'
      - run: |
          swift build -c release
          mv .build/release/protoc-gen-swift protoc-gen-swift-macos-${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: protoc-gen-swift-macos-${{ matrix.arch }}
          path: protoc-gen-swift-macos-${{ matrix.arch }}
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apple/swift-protobuf
          ref: '1.29.0'
      - run: |
          swift build -c release
          mv .build/release/protoc-gen-swift protoc-gen-swift-linux-${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: protoc-gen-swift-linux-${{ matrix.arch }}
          path: protoc-gen-swift-linux-${{ matrix.arch }}
  release:
    runs-on: ubuntu-latest
    needs:
      - macos
      - linux
    steps:
      - uses: actions/download-artifact@v4
      - run: ls -l; ls -l protoc-gen-swift-*
      - uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: '**/protoc-gen-swift-*'
